name: evently_sprint
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_number_input: ^0.7.3+1
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.10
  flutter_redux: ^0.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.1+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo.png"

flutter_native_splash:
  color: "#333333"
  image: "assets/png/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/gif/

  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/montserrat.ttf
